# Generated by Django 3.2.6 on 2021-08-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, verbose_name='Путь')),
                ('timestamp', models.TimeField(verbose_name='Дата-Время')),
                ('method', models.CharField(choices=[('GT', 'GET'), ('PS', 'POST'), ('PT', 'PUT'), ('DL', 'DELETE')], max_length=200, verbose_name='Метод')),
            ],
        ),
    ]
